# mysql 连接相关
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  #保险起见，请单独用一个数据库，并创建好
  database: database

  #如果你不知道该选项的作用，请不要修改它
  jdbc-option: '?allowPublicKeyRetrieval=true'

#HikariCP连接池的配置，如果你不知道原理，请不要修改
HikariCP:
  #最小空闲连接数
  minimum-idle: 3
  #最大连接数
  maximum-pool-size: 5

#请勿修改
version: 1